### ISSUE TITLE
side effects of overriding setindex!

### ISSUE THREAD

**Issue by YongHee-Kim** [devsisters/JSONPointer.jl#8]
```julia 
pkg>dev JSONPointer
julia>using JSONPointer
julia>arr = [j"/a", j"/b", j"/a"]
julia>unique(arr)
ERROR: TypeError: in new, expected Dict{JSONPointer.Pointer{Any},Nothing}, got a value of type Dict{String,Any}
```
`unique` construct a dictionary to remove duplicates, and it's broken because `setindex!(dict, v, p::Pointer)` has been overridden.  So I've [overriden unique too](https://github.com/devsisters/JSONPointer.jl/blob/658fb673506d0ad57074dac4f3cb81350c6f6800/src/pointer.jl#L146) to use unique in [here](https://github.com/devsisters/XLSXasJSON.jl/blob/bcb4818bfd6aeab041c8e98763f180f395f7a4d3/src/worksheet.jl#L277)

are there any more side-effects of `setindex!`? or it should be moved all together as [suggested from this PR](https://github.com/devsisters/JSONPointer.jl/pull/7)?

**Comment by odow** [comment]
Oops. I removed `Base.unique` because it wasn't tested and it didn't seem to be used anywhere. I can add it back. But what is the use-case?
